# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orderbook.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'orderbook.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0forderbook.proto\x12\torderbook\"q\n\x05Order\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x12\n\norder_type\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x10\n\x08quantity\x18\x04 \x01(\x03\x12\x0e\n\x06\x61\x63tion\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\"\x7f\n\x05Trade\x12\x10\n\x08trade_id\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x03\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x0e\n\x06\x61\x63tion\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\t\x12\x11\n\ttimestamp\x18\x07 \x01(\x03\"\x1b\n\nPricePoint\x12\r\n\x05price\x18\x01 \x01(\x01\x42!Z\x1forderbookpb/contracts;contractsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orderbook_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\037orderbookpb/contracts;contracts'
  _globals['_ORDER']._serialized_start=30
  _globals['_ORDER']._serialized_end=143
  _globals['_TRADE']._serialized_start=145
  _globals['_TRADE']._serialized_end=272
  _globals['_PRICEPOINT']._serialized_start=274
  _globals['_PRICEPOINT']._serialized_end=301
# @@protoc_insertion_point(module_scope)
